# Setup
title: Dirk Meister
tagline:
description: Dirk Meister's blog
url: https://dmeister.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Dirk Meister
  url: https://twitter.com/dirkmeister
  email: dirk.mst@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
